import './styles.css';
import './css/sidebar.css';
import './css/footer.css';
import './css/header.css';
import './css/searchForm.css';
import './css/fullCard.css';
import './css/close.css';
import './css/card.css';
import './js/core';
